include/gemmi/cif.hpp
Brief: There is an ambiguity of `plus` symbol in cif.hpp. 
If **gemmi** is compiled as headers only and part of another project `plus` symbol in cif.hpp might raise an ambiguity error since there are might be at least two candidates (depends on a project): `pegtl::plus` and `std::plus`. Having explicitly specified `pegtl::plus` helps to remove the error.
Actually, I would advise removing 
`using namespace pegtl;`
and other `using namespace` from headers altogether and prepending typenames explicitly since otherwise it may raise namespace clashes and thus such ambiguity errors.
=> Removed ambiguity of plus symbol: explicitly set to pegtl::plus

include/gemmi/cifdoc.hpp
There is no check if **positions** vector is filled or not, which leads to throwing an exception for non-valid .cif files (e.g., https://files.rcsb.org/ligands/download/HEM.cif).
=> Fix: Table::has_column throws exception when positions vector is empty

include/gemmi/to_mmcif.hpp
After some feedback from wwPDB.
PS: this is my first time try this collaborative work on github.com ... please let me know if it goes bonkers ;-)
=> Removed superfluous "ls_" prefix from _refln_ls_shell Category group

.appveyor.yml, .travis.yml, setup.py
The `setup.py` included with gemmi requires the user to pre-install pybind11 if it is missing, or does not meet the minimum version requirement. This pull request updates the `setup.py` to automatically install pybind11 if it is missing from the environment prior to installing gemmi. 
The updates made to the `setup.py` file are based on this [example](https://github.com/pybind/python_example/blob/master/setup.py). The important change is to include a `setup_requires` argument in the main `setup()` call. I have also updated the `get_pybind_include` object to match the example. 
The final changes made in this pull request are to the CI .yml scripts for appveyor / TravisCI. I removed the manual `pip install pybind11` calls so that it will be possible to see the effects of these changes. 
I …
=> Installation of pybind11 in setup.py

python/cif.cpp, python/gemmi.cpp, python/grid.cpp, python/hkl.cpp, python/mol.cpp, python/monlib.cpp, python/unitcell.cpp
Valid signatures in docstrings are crucial for static analysis tools and doc generators. 
[this PR]:
```
$ python show_gemmi_help.py | grep '::' | wc -l
0
```
[master]:
```
$ python show_gemmi_help.py | grep '::' | wc -l
358
```
<details><summary> [master] <code>python show_gemmi_help.py | grep '::' | head</code></summary>
```
|      make_assembly(self: gemmi.Assembly, arg0: gemmi::Model, arg1: gemmi.HowToNameCopiedChains) -> gemmi::Model
|      2. __init__(self: gemmi.AtomAddress, arg0: gemmi::Chain, arg1: gemmi::Residue, arg2: gemmi::Atom) -> None
|      3. __init__(self: gemmi.AtomAddress, chain: str, seqid: gemmi::SeqId, resname: str, atom: str, altloc: str = '\x00') -> None
|      1. __getitem__(self: gemmi.AtomGroup, index: int) -> gemmi::Atom
|      2. __getitem__(self: …
```
=> Reduce number of C++ signatures in generated docstrings

setup.py
so drop it from `install_requires` (keeping it in `setup_requires`)
=> pybind11 is not a runtime dependency

include/gemmi/model.hpp, include/gemmi/to_mmcif.hpp, include/gemmi/to_pdb.hpp
LINKR records with a link id of "gap" do not have atom names, but should be kept.
=> write LINK(R) records even when atom names missing

include/gemmi/to_pdb.hpp
The HEADER line lost a line break when entry_id was too long
=> Fixed HEADER record writing

include/gemmi/symmetry.hpp
It returned "P 2 1 1" when e.g. mrc file (space group header: 0) was opened. This would be not what is expected.
=> return P1 space group when number 0 requested

python/mol.cpp
I wanted this for keeping metadata (e.g. read structure from refmac mmcif, add raw_remarks from pdb, and write both pdb/mmcif).
=> Add python binding for Structure::raw_remarks

python/sym.cpp, python/unitcell.cpp, tests/test_symmetry.py, tests/test_unitcell.py
I've been curious about adding pickling support to a few of the `gemmi` classes that are used in `reciprocalspaceship` to allow us to pickle our `DataSet` objects. My revisions to the python interface are based on https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support.
This seems to mostly work -- however, on my fork it seems to be failing CI in Ubuntu 16.04/Clang 3.5. Please let me know if you have any thoughts on what seems to be going on.
=> Add pickling support to SpaceGroup and UnitCell

include/gemmi/placeh.hpp, python/topo.cpp
It would be convenient in case nucleus distances are not available in the monomer library. A good scale would be ~1.1 to electron distances.
=> add default_scale option to adjust_hydrogen_distances()

include/gemmi/placeh.hpp
Currently gemmi only adds hydrogen to the first altloc.
=> Fix to add hydrogens to all altlocs

include/gemmi/topo.hpp
I think it is useful not to throw an exception if monomer not found. We may need to show a warning, or make this behavior optional?
=> topo: do not stop when monomer is not defined

include/gemmi/to_pdb.hpp
I saw a program (accidentally) set long atom name and gemmi write a broken pdb file. So this should be safer.
=> to_pdb: limit the atom name length

include/gemmi/to_mmcif.hpp
- "_struct_conn."ccp4_link_id was missing
- con.name may be empty (should not?)
=> bug fix in mmcif writing

include/gemmi/to_mmcif.hpp
did the same thing as 3a2a23c1
=> to_mmcif: avoid checking segment (for #121)

python/mol.cpp
Add `Chain.calculate_center_of_mass()` analogues to `Model.add_calculate_center_of_mass()`
(I needed this to conveniently conditionally move chains between unit cells)
=> Add Chain.calculate_center_of_mass python binding

include/gemmi/topo.hpp
With the current code, phosphate group of 5' end is ignored when creating topology
=> topo: Fix modification of 5' end of RNA/DNA

include/gemmi/placeh.hpp, include/gemmi/topo.hpp, python/topo.cpp
Topo::initialize_refmac_topology adds bonds to monomer library if the link is not defined. This PR is to make it optional.
=> add ignore_unknown_links to prepare_topology/initialize_refmac_topology

python/gemmi.cpp
=> SmallStructure: add missing python bindings

include/gemmi/to_mmcif.hpp
invalid cif was written when model.name was empty
=> to_mmcif: fix for empty model.name

include/gemmi/to_pdb.hpp
LINK records may miss newline when distance>100 Å. It should not happen, but I think it should not break PDB file in any case. I added this to others just in case.
=> to_pdb: ensure newline

include/gemmi/to_mmcif.hpp
To avoid writing broken cif file in case residue name is empty. It happened when using a pdb file converted from shelx res file.
=> to_mmcif: quote residue name

include/gemmi/monlib.hpp
New monomer library (in bzr, not yet in ccp4) includes nucleus distances for modifications.
=> monlib: read nucleus distances in modifications

include/gemmi/binner.hpp, python/hkl.cpp
In addition, I think cell should be always given when setup or there should be a flag, because `get_bin_numbers()` may be called even when binner was setup without cell.
I also added python binding for `binner.setup_from_1_d2`, but it was much slower. Probably memory copy occurred? Do you know how to improve this?
```
In []: %timeit binner.setup(20, gemmi.Binner.Method.Dstar2, mtz)
29.1 ms ± 291 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In []: %timeit binner.setup_from_1_d2(20, gemmi.Binner.Method.Dstar2, mtz.make_1_d2_array())
224 ms ± 2.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
=> Binner: add get_bin_number_from_1_d2 etc

include/gemmi/placeh.hpp
Sometimes atoms removed by modification are reported. We need chain/residue information to track the error.
=> prepare_topology: more detailed message

include/gemmi/topo.hpp
It may be safe to do case insensitive comparison though.
=> topo: do not apply NH3 mod to M-peptide

include/gemmi/monlib.hpp
In my understanding, group matching should be done only when `comp` is unspecified. Correct?
=> monlib: fix link_side_matches_residue

include/gemmi/monlib.hpp
Now peptide's group name may be L-peptide as well as peptide.
=> monlib: support L-peptide

include/gemmi/mmcif.hpp
It tried to read distance from a wrong position.
=> mmcif: fixed reading of _struct_conn.pdbx_dist_value

include/gemmi/to_pdb.hpp
Allow app developers to decide whether or not the CRYST1 record is written to pdb
=> Make writing CRYST1 record optional

include/gemmi/monlib.hpp, include/gemmi/resinfo.hpp, python/elem.cpp, python/monlib.cpp
Now monomer library has ketopyranose group, and gemmi could not identify e.g. ALPHA2-3 link as seen in SIA-GAL of 6xtg.
=> add ketopyranose to ResidueInfo and ChemLink::Group

include/gemmi/to_chemcomp.hpp
=> make_chemcomp_with_restraints: use element name as chem_type

include/gemmi/modify.hpp
- Sometimes (or in most cases?) deuterium atom names start with D. 
- Only D is there in some cases.
=> collapse_hd_mixture: for use in more cases

include/gemmi/xds_ascii.hpp, prog/xds2mtz.cpp
XDS_ASCII.HKL files do not have MAXC, here's a kludge to fix it for the moment.
=> xds2mtz fixup reading XDS_ASCII.HKL that does not have MAXC column.

include/gemmi/xds_ascii.hpp, prog/xds2mtz.cpp
Hi Marcin, please pull this branch. It adds a new option to xds2mtz:
--batchmin=BATCHMIN      Delete reflections with BATCH<BATCHMIN (default: 1)
It sometimes happens that a few reflections have a negative Z-value. This gives rise to BATCHES with a value of zero or lower. 
Downstream programs can have problems with this.
By default pointless does the same.
Regards,
ClAuS
=> xds2mtz: New option --batchmin to delete batches with BATCH<BATCHMIN Default 1.

include/gemmi/asumask.hpp, include/gemmi/atox.hpp, include/gemmi/fileutil.hpp
cstdint has to be included explicitly, see:
https://gcc.gnu.org/gcc-13/porting_to.html
=> Fix compilation with GCC 13

python/meta.cpp
This is a very small change, but I found that it made it easier to keep track of what was going on in my scripts, so I thought I'd be worth contributing back.
=> Give the `Assembly` class a nicer string representation

src/mmcif.cpp
I found that Foldseek does not extract any chains from PyMol exported mmCIF files. Tracking the issue down to gemmi seems to be due to gemmi requiring `auth_seq_id` to be present, but PyMol not saving it.
I tested the PR within Foldseek and everything works as expected.
I also attached a mmCIF file exported from PyMol that has the issue.
[pymol_wo_auth_seq_id.cif.txt](https://github.com/user-attachments/files/16139475/pymol_wo_auth_seq_id.cif.txt)
=> PyMol saves mmCIF without auth_seq_id, fall back to label_seq_id

prog/mtz.cpp
Usually, resolution values are given in order low-resolution (low d* value, low diffraction angle) to high-resolution (high d* value, high angle) ... even if the d values (in Angstroem) run the other way ;-)
=> Slightly nicer (I think) formatting of a few items.
