include/gemmi/contact.hpp, include/gemmi/subcells.hpp, python/grid.cpp, python/monlib.cpp
Note: first commit is a breaking change. Possible alternatives seems to be worse to me (exposing `gemmi::El` to python / dynamic construction of `gemmi::Element` in `gemmi.SubCells.element` lambda)
(This PR fixes remaining C++ signatures that leaked to python docstring)
=> Enum fixes

include/gemmi/small.hpp
=> Fix out-of-bounds string access

python/grid.cpp
constructors from grid size and from numpy.array
=> python: add ReciprocalGrid constructors

python/unitcell.cpp
For Transform, Mat33, Vec3 classes
=> Add python bindings for approx() and is_identity()

include/gemmi/assembly.hpp
there must be a smarter way to initialize SMat33\<float\> from SMat33\<double\>?
=> Apply ncs operator to aniso

python/common.h, python/grid.cpp, python/hkl.cpp, python/unitcell.cpp
AsuData.copy() a copy constructor, SMat33.r_u_r() for numpy.array, Mat33 as numpy.array.
=> Adding python functions

include/gemmi/ccp4.hpp
otherwise grid.spacing is not set.
=> ccp4.hpp: use set_size_without_checking

python/unitcell.cpp
parameters property and operator==()
=> add python functions for UnitCell

python/grid.cpp
- Grid properties: shape and spacing
- Add cell and sg arguments for Grid constructor 
- Grid. point_to_position() directly from u, v, w
=> add python functions for Grid

include/gemmi/unitcell.hpp, python/unitcell.cpp
To keep Position object after operation. Related to #72.
=> operator overloads for Position

python/mol.cpp
I think this is useful, but perhaps it should not be a member function of Model?
=> Add transform() for pyModel

python/elem.cpp
=> Add python binding for Element.is_hydrogen

include/gemmi/sfcalc.hpp, python/sf.cpp
I needed this to test different occupancies for f_xray part and Z part. Because I wanted to scale atomic scattering factors so that sum(a)+c equals to Z.
I hope this form is considered more general?
=> calculate_mb_z_from_h to calculate_mb_z, to apply for all atoms

python/grid.cpp
=> Fixed a typo

python/ccp4.cpp
full_cell() and axis_positions() were added.
=> Add missing python bindings for ccp4

include/gemmi/grid.hpp, python/grid.cpp
I want to have this for EM map manipulations.
=> Grid::subgrid() added

python/monlib.cpp
=> python bindings for Angles/Torsion/Chirality/Plane

python/mol.cpp
for find_best_plane() and get_distance_from_plane()
=> Add python bindings

python/sf.cpp
for add_atom_density_to_grid()
=> add a python binding

python/topo.cpp
to make Topo::chain_infos available in python
=> added missing Topo python bindings

include/gemmi/dencalc.hpp, python/sf.cpp
Just wanted to know a radius before calculation
=> dencalc: add python binding for estimate_radius()

python/gemmi.cpp
Should I make a separate function?
=> python: vectorize bessel_i1_over_i0

include/gemmi/topo.hpp
=> topo: ignore segment in find_cra

include/gemmi/monlib.hpp, python/monlib.cpp
to read links/modifications into monlib etc.
=> monlib: add python bindings

include/gemmi/grid.hpp
=> grid: fix copy_4x4x4

python/monlib.cpp
=> python: fixed Restraints::Torsion

python/unitcell.cpp
bindings for operator- and operator+.
=> python: operators for Fractional

include/gemmi/monlib.hpp, include/gemmi/topo.hpp, python/elem.cpp, python/monlib.cpp
and related python bindings including one bug fix
=> topo: first try to find the link by id

python/meta.cpp
with necessary pickling supports
=> python: add pickling support to AtomAddress

include/gemmi/chemcomp.hpp, include/gemmi/topo.hpp, python/monlib.cpp, python/topo.cpp
Since Restraints::chiral_abs_volume() does not work for link-related chirals, I added Topo::ideal_chiral_abs_volume() which uses take_bond() and take_angle().
=> add Topo::ideal_chiral_abs_volume() and Topo::Chirality::calculate_z()

include/gemmi/math.hpp
SMat33.multiply(Vec3) and SMat33+/-SMat33
=> functions added to SMat33

python/hkl.cpp
I want to use the intensity merging function. Is it ok to add its python binding? I can change wherever needed.
=> python: add Intensities

include/gemmi/fourier.hpp, include/gemmi/recgrid.hpp, python/recgrid.cpp
This enables faster updating of Fcalc etc. I may have missed something.
=> add ReciprocalGrid.get_value_by_hkl

include/gemmi/refln.hpp
always failed to read space group
=> refln: fix hkl_cif_as_refln_block

include/gemmi/chemcomp.hpp
At least Refmac uses it in output mmcif files.
=> chemcomp: support mmcif compliant chirality

python/meta.cpp
for SeqId, ResidueId, and AtomAddress.
=> python: add operator overloads

include/gemmi/scaling.hpp
=> scaling: fix fit_isotropic_b_approximately

include/gemmi/grid.hpp, python/grid.cpp
I want to use this to change sampling for mask (for normal maps FFT-based resampling would work). Is it ok with you? I will make changes wherever necessary.
=> add Grid::upsample_nearest()

include/gemmi/monlib.hpp
As I wanted to use these values. By the way, currently `estimate_distance()` is used for atom names, but chemical types should be used, no?
=> monlib: add struct EnerLib

python/cif.cpp, tests/test_cif.py
e.g 'ALA' in doc -> True/False
=> python: added contains operator to cif.Document

include/gemmi/xds_ascii.hpp, prog/xds2mtz.cpp, src/xds_ascii.cpp
Hi Marcin
Please pull this branch to get more options for the xds2mtz feature.
Thanks,
ClAuS
=> Xds2mtz add on
